### ISSUE TITLE
Clarification on sparse keyframe in-betweening

### ISSUE THREAD

**Issue by setarehc** [c-he/NeMF#16]
Hi,
Thanks for this great work and your codebase!
In the sparse keyframe setting of the inbetweening experiments (refering to Table 5 in the paper), how are keyframes exactly selected? Do you select the first frame and then, select the next frame every t = {5, 10, 15, 20} frames? This way, when t = 5 and motion length is some arbitrary length, the mask will look like this: [1,0,0,0,0,1,0,0,0,0,1,...]
I'm asking this as I'm trying to compare my own inbetweening model with yours and I want to make sure I'm exactly replicating your setup. 
Thanks :)

**Comment by c-he** [comment]
Hi, thanks for your interest in our work! You can find the keyframe selection code in our `application.py`:

https://github.com/c-he/NeMF/blob/79918430970fd138ae730510459c8f34893a3f86/src/application.py#L440-L442

We fix the first and last frames as they are required for SLERP, and the rest of the keyframes are sampled every $t$ frames.
