### ISSUE TITLE
About inference on video

### ISSUE THREAD

**Issue by henrycjh** [c-he/NeMF#3]
Thanks for your great work!
Could you please give me some suggestions on how to run NeMF on an arbitrary video (for motion reconstruction task)? It seems that application.py use data from AMASS.

**Comment by c-he** [comment]
Thanks for your interest in our work! Currently we only tested reconstruction on [AIST++](https://google.github.io/aistplusplus_dataset/factsfigures.html), which has ground truth SMPL data associated with each video. They released their [code](https://github.com/google/aistplusplus_api) for pose estimation on original videos, maybe you can take a look.
